language:    # 指明使用的语言
  - go

go:          # 语言版本号
  - "1.12.x"   # 默认使用最新版本,注意，需要 "1.10" 版本的时候必须表示为字符串形式，如果写成 1.10 则会使用 1.1 版本;x表示对应前缀的最新版本
  - "1.13.x"

env:
  - service_name=System.getenv(service_name)
  - repo_token=System.getenv(repo_token)
  - GO111MODULE=on

before_script:
  - go get ./...

script:      # 执行的脚步，但是go默认会执行下面的这些命令的，所以可以不用写
  - go test -v ./...